bigblog/urls.py
from django.urls import path, re_path
from . import views;

app_name = "bigblog"
urlpatterns = [
	#post views
	path('user_login/', views.user_login, name = "user_login"),
	path('user_register/', views.register, name = "register"),
	path('blog/', views.post_list, name = "post_list"),
	path('blog/<int:pk>/edit', views.post_edit, name = "post_edit"),
	path('blog/new/', views.post_new, name = "post_new"),


	re_path(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
	re_path(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'\
        r'(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),

	#path('blog/', views.PostListView.as_view(), name = "post_list"),
]

messenger/urls.py
from django.contrib import admin
from django.urls import path,  include

urlpatterns = [
    path('admin/', admin.site.urls),
  	path('', include('bigblog.urls', namespace = "bigblog")),
]	

bigblog/models.py
from django.urls import reverse
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User



class Likes(models.Model):
	pass

class Post(models.Model):
	STATUS_CHOICES = (
		("draft", "Draft"),
		("published", "Published"),
	) 
	title = models.CharField(max_length = 50)
	slug = models.SlugField(max_length = 250, unique=True, null=True)
	author = models.ForeignKey(User, on_delete = models.CASCADE,  related_name = "blog_posts")
	body = models.TextField()
	publish = models.DateTimeField(default = timezone.now)
	created = models.DateTimeField(auto_now_add = True)
	updated = models.DateTimeField(auto_now = True)
	status = models.CharField(max_length = 10, choices = STATUS_CHOICES, default = "draft")


	def get_absolute_url(self):
		return reverse('bigblog:post_detail', args =[self.publish.year,self.publish.strftime('%m') ,self.publish.strftime('%d'),self.slug])
		
	class Meta:
		ordering: ('-publish',)

	def __str__(self):
		return self.title



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

bigblog/forms.py
from django import forms
from .models import Post, Comment
from django.contrib.auth.models import User

#class send message to email post 
class EmailPostForm(forms.Form): 
    name = forms.CharField(max_length = 25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required = False, widget = forms.Textarea)
    



# class for sign in sign out
class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget = forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']



class PostForm(forms.ModelForm):

    class Meta: 
        model = Post
        fields = ('title', "slug", 'body', "status")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

bigblog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse 
from django.contrib.auth import authenticate, login
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.utils import timezone

from .forms import LoginForm, UserRegistrationForm, EmailPostForm, PostForm, CommentForm
from .models import Post, Comment



# Create your views here.

# class PostListView(ListView): 
#     queryset = Post.objects.all()
#     context_object_name  = "posts"
#     paginate_by = 3
#     template_name = "bigblog/post/list.html"


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                   # return render(request, "bigblog/login.html", {"form": form});
                    return post_list(request);
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'bigblog/login.html', {'form': form})

 

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            return render(request, 'bigblog/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'bigblog/register.html', {'user_form': user_form})


def post_list(request):
    object_list = Post.objects.all()
    paginator = Paginator(object_list, 3)      # 3 posts in each num_pages 

    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        #if page is not a integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        #if page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, "bigblog/post/list.html", {"page": page, 'posts': posts})



def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)

    #List of active comments for this post
    comments = post.comments.filter(active = True)

    if(request.method == "POST"):
        #A comment was posted
        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            #Create Comment object but don't save to databave yet
            new_comment = comment_form.save(commit = False)
            #Assign the current post to the comment
            new_comment.post = post
            #Save the comment to database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, "bigblog/post/detail.html", 
                            {'post':post, 
                              'comments': comments,
                              'comment_form': comment_form})


def post_share(request, post_id):
    #Retreive post by id
    post = get_object_or_404(Post, id = post_id, status = "published")
    sent = False
    if request.method == "POST":
        #Form was submitted 
        form = EmailPostForm(request.POST)
        if form.is_valid():
            #Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, "tyazhinazhanel@gmail.com", [cd['to']])
            send = True
           # ... send email

    else: 
        form = EmailPostForm()

    return render(request, "bigblog/post/share.html", {
                            "post": post, 
                            "form": form,
                            'sent': sent})


def post_edit(request, pk):
    post = get_object_or_404(Post, pk = pk)

    if(request.method == 'POST'):
        form = PostForm(request.POST, instance = post)

        if(form.is_valid()):
            post = form.save(commit = False)
            post.author = request.user
            date = timezone.now()
            post.save()
            return render(request, "bigblog/post/detail.html", {"post": post})
            #return redirect("bigblog:post_detail", post = post.get_absolute_url)
    else:
        form = PostForm(instance = post)

    return render(request, "bigblog/post/post_edit.html", {"form": form});



def post_new(request):
    if(request.method == "POST"):
        form = PostForm(request.POST)

        if(form.is_valid()):
            post = form.save(commit = False)
            post.author = request.user
           # post.slug = request.title 
            post.save()
            #return redirect('bigblog:post_detail', post.get_absolute_url) 
            return render(request, "bigblog/post/detail.html", {"post": post})
    else:
        form = PostForm()
    
    return render(request, "bigblog/post/post_edit.html", {"form": form});   

bigblog/templates/bigblog/post/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'scss/build/css/blog.css' %}" rel="stylesheet">
</head>
<body>
<div id="content">

    <div class = "page-header"> 
        {% if user.is_authenticated %}
            
            <a href = "{% url 'bigblog:post_new' %}" class = "top -menu">
                <span class = "glyphicon glyphicon-plus" style= "font-size: 20px; margin: 30px;">+ NEW POST</span>
            </a>

        {% endif %}

        <h1 style = "margin: 30px;">
            <a href = "/blog/">zeroToHero</a>
        </h1>

    </div>

    {% block content %}

    {% endblock %}
</div>
<div id="sidebar">
    <h2>My blog</h2>
    <p>This is my blog.</p>
</div>
</body>
</html>

bigblog/templates/bigblog/post/detail.html
{% extends "bigblog/post/base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    

    {% if user.is_authenticated %}

        <a href = "{% url 'bigblog:post_edit' pk=post.id %}" class = "btn btn-defaul">
            <span class = "glyphicon glyphicon-pencil" style = "margin: 30px;">EDIT POOST</span>  
        </a>

    {% endif%}


    <a href = "{% url 'bigblog:post_list' %}">Back</a>

    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>


    {{ post.body|linebreaks }}



    <!-- DJANGO ORM -->
    {% with comments.count as total_comments %}
        <h2>
            <!-- а pluralize используется для отображения суффикса -->
            {{total_comments}} comment {{total_comments|pluralize}}
        </h2>
    {%endwith%}

    {% for comment in comments %}
        <div class = "comment">
            <p class = "info">
                Comment {{ forloop.counter }} by {{ comment.name }} 
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
        {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Your comment has been added.</h2>

    {% else %}
        <h2>Add a new comment</h2>
        <form action = "." method = "POST">
            {{comment_form.as_p}}

            {%csrf_token%}

            <p><input type= "submit" value = "Add comment" /> </p>
        </form>
    {% endif %}
 <!--        {% if user.is_authenticated%}

            <form method = "POST">
                {% csrf_token %}
                
                <a href = "{% url 'bigblog:post_list' %}"><button  type = "submit" class = "btn btn-default">Delete</button></a>
                
            </form>
            
        {% endif %} -->


    <p>
        <a href = "{% url 'bigblog:post_share' post.id %}">Share this post</a>
    </p>

{% endblock %}

bigblog/templates/bigblog/post/list.html
{% extends "bigblog/post/base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}
    <nav>
         <ul>
            <li><a href = "{% url 'bigblog:register' %}">Sign up</a></li>
            <li><a href = "{% url 'bigblog:user_login' %}">Sign in</a></li>
         </ul>

    </nav>
    <h1>My Blog</h1>
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}

    {% include 'bigblog/post/pagination.html' with page=posts %}
{% endblock %}

bigblog/templates/bigblog/post/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

bigblog/templates/bigblog/post/post_edit.html
{% extends 'bigblog/post/base.html'%}

{% block content %}
	<h1>New post1</h1>
	<form method = "POST" class = "post-form">
		{% csrf_token %}
		{{ form.as_p }}

		<button type = "submit" class = "save btn btn-default">Save</button>

	</form>
		
{% endblock %}

bigblog/templates/bigblog/post/share.html
{% extends 'bigblog/post/base.html' %}
{% block title %}Share a post {% endblock %}
{% block content %}
	{%if sent %}
		<h1>E-mail successfully sent</h1>
		<p>
			"{{ post.title }}" was successfully sent to {{ cd.to }}.
		</p>

	{% else %}

	<h1>Share "{{ post.title }}" by e-mail</h1>

	<form action = "." method = "post">
		{{form.as_p}}
		{%csrf_token%}
		<input type = "submit" value = "Send e-mail" />
	</form>

	{% endif %}
{% endblock %}